language: python

matrix:
    include:
        # 64-bit Linux builds
        - os: linux
          python: 2.7
        - os: linux
          python: 3.3
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6
          env: RUN_FLAKE=1

        # 64-bit Mac OS X builds
        - os: osx
          language: generic
          env: PYENV_VERSION=2.7.13
        - os: osx
          language: generic
          env: PYENV_VERSION=3.3.6
        - os: osx
          language: generic
          env: PYENV_VERSION=3.4.6
        - os: osx
          language: generic
          env: PYENV_VERSION=3.5.3
        - os: osx
          language: generic
          env: PYENV_VERSION=3.6.1

cache:
    - pip
    - directories:
        - $HOME/.pyenv_cache

before_install:
    - chmod a+x ./ci/travis_install.sh

install:
    - ./ci/travis_install.sh

script:
    - python ttasks.py test
    - if [[ $RUN_FLAKE ]]; then flake8 .; fi
