os:
  - linux

language:
  - python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"

matrix:
  include:
    - python: "3.6"
      env: RUN_FLAKE=1

install:
  - if [[ $RUN_FLAKE ]]; then pip install flake8; fi

script:
  - python ttasks.py test
  - if [[ $RUN_FLAKE ]]; then flake8 .; fi
