language: python

matrix:
    include:
        # 32-bit Linux builds
        - os: linux
          python: 2.7
          sudo: required
          env: $TT_32_BIT=1
        - os: linux
          python: 3.3
          sudo: required
          env: $TT_32_BIT=1
        - os: linux
          python: 3.4
          sudo: required
          env: $TT_32_BIT=1
        - os: linux
          python: 3.5
          sudo: required
          env: $TT_32_BIT=1
        - os: linux
          python: 3.6
          sudo: required
          env: $TT_32_BIT=1

        # 64-bit Linux builds
        - os: linux
          python: 2.7
        - os: linux
          python: 3.3
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6
          env: RUN_FLAKE=1

install:
    - ./ci/travis_install.sh

script:
    - python ttasks.py test
    - if [[ $RUN_FLAKE ]]; then flake8 .; fi
