environment:
    PYPI_PW:
        secure: MMD+XFYORERejvD2Wb6/u9UDLQwOnm9ASdQf2AqRtWk=

    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python27-x64"
        - PYTHON: "C:\\Python33"
        - PYTHON: "C:\\Python33-x64"
          DISTUTILS_USE_SDK: "1"
        - PYTHON: "C:\\Python34"
        - PYTHON: "C:\\Python34-x64"
          DISTUTILS_USE_SDK: "1"
        - PYTHON: "C:\\Python35"
        - PYTHON: "C:\\Python35-x64"
        - PYTHON: "C:\\Python36"
        - PYTHON: "C:\\Python36-x64"
          RUN_FLAKE: "1"

install:
    - "if \"%RUN_FLAKE%\"==\"1\" %PYTHON%\\python.exe -m pip install flake8"
    - "%PYTHON%\\python.exe -m pip install wheel"
    - "ci\\win_build.cmd %PYTHON%\\python.exe setup.py build"
    - "ci\\win_build.cmd %PYTHON%\\python.exe setup.py develop"

build: off

test_script:
    - "%PYTHON%\\python.exe ttasks.py test"
    - "if \"%RUN_FLAKE%\"==\"1\" %PYTHON%\\Scripts\\flake8.exe ."

on_success:
    - echo [distutils]                              > %USERPROFILE%\\.pypirc
    - echo index-servers =                         >> %USERPROFILE%\\.pypirc
    - echo     pypi                                >> %USERPROFILE%\\.pypirc
    - echo [pypi]                                  >> %USERPROFILE%\\.pypirc
    - echo repository=https://pypi.python.org/pypi >> %USERPROFILE%\\.pypirc
    - echo username=welchbj                        >> %USERPROFILE%\\.pypirc
    - echo password=%PYPI_PW%                      >> %USERPROFILE%\\.pypirc

    - set HOME=%USERPROFILE%

    - "if \"%APPVEYOR_REPO_TAG%\"==\"true\" ( ci\\win_build.cmd %PYTHON%\\python.exe setup.py sdist bdist_wheel upload )"
